### ISSUE TITLE
boost::json::serialize returns NULL string

### ISSUE THREAD

**Issue by marincovic** [boostorg/json#825] opened 2022-12-22 10:28 UTC
PLEASE DON'T FORGET TO "STAR" THIS REPOSITORY :)
Hello Team,
I am having issues when trying to serialize my JSON into a string before sending it.
The problem is that the serialize command returns a NULL string.
From what I can see the string is not empty it only say unable to read memory.
![image](https://user-images.githubusercontent.com/12939900/209114314-413e199f-75b1-4831-8f48-3fde2863bbfd.png)

### Version of Boost

1.81.0

### Steps necessary to reproduce the problem
All elements in the map are std::string.
```
	boost::json::object JSONObject;
	JSONObject["type"] = this->PV_DTOMessageType;
	for (auto iter = keyValueMap.begin(); iter != keyValueMap.end(); ++iter) {
		JSONObject[iter->first] = iter->second;
	}
	return boost::json::serialize(JSONObject);
```

**Comment by grisumbras** [comment] 2022-12-22 11:03
What is a "NULL string"? I'm pretty sure we can't create an invalid `std::string`. Can you create a minimal reproducible example, so that I can investigate your issue?

**Comment by grisumbras** [comment] 2023-01-02 11:44
Wait, do I understand you correctly that you build Boost.JSON for one platform, but build your program that links to Boost.JSON for another platform? If you do — don't. That's never guaranteed to work. And even if it seems to work, most likely it silently has errors.

**Comment by grisumbras** [comment] 2023-05-31 12:20
@marincovic have you figured out why you were having this error?

**Comment by marincovic** [comment] 2023-05-31 14:26
Hello,

Sorry I did not post it anything sooner. I could not resolve the issue at all, so I had to switch JSON tools. From what I remember the issue was connected to the DLL that was being used (I tried building it with Clang-cl as well but there was still an issue).
Unfortunately it was some time ago so I am not 100% sure.

Once again sorry for the late response.
BR//
Marin

**Comment by grisumbras** [comment] 2023-06-01 08:44
It seems like the issue was caused by using an incompatible binary. I'm closing this for now.

**Closed by grisumbras** 2023-06-01 08:44 UTC
