### ISSUE TITLE
remove type aliases

### ISSUE THREAD

**Issue by alandefreitas** [boostorg/json#958] opened 2023-12-14 14:31 UTC
we should get rid of our aliases for error_code, result, et. al. and just use them directly from system.

This is just a replicate of this issue: https://github.com/boostorg/url/issues/743

The solution for Boost.URL was: https://github.com/boostorg/url/commit/96438f683e09e20183fab1b6059fa7f1b0ffe67d

**Comment by grisumbras** [comment] 2023-12-15 13:08
Duplicate of #881

**Closed by grisumbras** 2023-12-15 13:08 UTC
