### ISSUE TITLE
Fast and lean pow10

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/json#341] opened 2020-09-15 14:08 UTC
We need a replacement for the big lookup table for performing `double pow10( int )` which is reasonably fast and doesn't take up 5Kb.

**Comment by madmongo1** [comment] 2020-09-15 16:08
maybe helpful: 
http://szhorvat.net/pelican/fast-computation-of-powers.html

**Comment by vinniefalco** [comment] 2020-09-15 16:20
> http://szhorvat.net/pelican/fast-computation-of-powers.html

Doesn't load for me

**Comment by vinniefalco** [comment] 2020-09-15 16:22
We want IEEE `pow10` which means `double`

**Comment by grisumbras** [comment] 2021-02-25 05:52
Is this a duplicate of #353 ?

**Comment by grisumbras** [comment] 2021-02-25 10:33
FYI, I tried halving the table and calculating powers of 10 via `auto x = pow10(e/2); return x * x * pow10(e%2);`
Locally it decreased speed of parsing `numbers.json` by 5-6%, but more importantly a lot of tests started failing, because parsing accuracy has decreased due to extra multiplications (3 ULP difference with `strtod`).

```
# develop
479K libs/json/build/gcc-10/release/link-static/visibility-hidden/libboost_json.a
530K libs/json/bench/gcc-10/release/link-static/bench
Parse bench/data/canada.json,gcc x64/sse2,boost,201
Parse bench/data/numbers.json,gcc x64/sse2,boost,374

# PR #505
476K libs/json/build/gcc-10/release/link-static/visibility-hidden/libboost_json.a
530K libs/json/bench/gcc-10/release/link-static/bench
Parse bench/data/canada.json,gcc x64/sse2,boost,194 (-3.5%)
Parse bench/data/numbers.json,gcc x64/sse2,boost,378 (+1%)

# PR #505 + additional halving of exponents
476K libs/json/build/gcc-10/release/link-static/visibility-hidden/libboost_json.a
526K libs/json/bench/gcc-10/release/link-static/bench
Parse bench/data/canada.json,gcc x64/sse2,boost,197 (-1.9%)
Parse bench/data/numbers.json,gcc x64/sse2,boost,355 (-5%)
```

**Comment by grisumbras** [comment] 2021-04-26 06:21
I think, this should be closed. The approach we use currently results in higher precision.

**Comment by vinniefalco** [comment] 2021-04-26 06:28
Close it

**Closed** 2021-04-26 06:33 UTC
